// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package usecase

// Injectors from wire.go:

func createTodoService() *TodoService {
	todoService := newTodoService()
	return todoService
}
