// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package usecase

import (
	"github.com/iwaltgen/grpc-go-web-todo/pkg/repository"
)

// Injectors from wire.go:

func createTodo() *Todo {
	todo := repository.DefaultTodo()
	usecaseTodo := newTodo(todo)
	return usecaseTodo
}
