# Working directory
root = "."
watch_dir = "pkg"
tmp_dir = "tmp"

[build]
cmd = "mage buildDev"
bin = "tmp/server"
include_ext = ["go", "tpl", "tmpl"]
exclude_dir = ["tmp", "api", "bin", "build", "cmd", "node_modules", "public", "src"]
exclude_file = ["mage_output_file.go"]
delay = 500 # ms
send_interrupt = true
kill_delay = 250 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
