// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: todo/v1/event.proto

package todov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event int32

const (
	Event_EVENT_UNSPECIFIED Event = 0
	Event_EVENT_CREATE      Event = 1
	Event_EVENT_UPDATE      Event = 2
	Event_EVENT_DELETE      Event = 3
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0: "EVENT_UNSPECIFIED",
		1: "EVENT_CREATE",
		2: "EVENT_UPDATE",
		3: "EVENT_DELETE",
	}
	Event_value = map[string]int32{
		"EVENT_UNSPECIFIED": 0,
		"EVENT_CREATE":      1,
		"EVENT_UPDATE":      2,
		"EVENT_DELETE":      3,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_todo_v1_event_proto_enumTypes[0].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_todo_v1_event_proto_enumTypes[0]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_todo_v1_event_proto_rawDescGZIP(), []int{0}
}

var File_todo_v1_event_proto protoreflect.FileDescriptor

var file_todo_v1_event_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x2a, 0x54,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45,
	0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x44, 0x45, 0x4c, 0x45,
	0x54, 0x45, 0x10, 0x03, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x77, 0x61, 0x6c, 0x74, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2d, 0x67, 0x6f, 0x2d, 0x77, 0x65, 0x62, 0x2d, 0x74, 0x6f, 0x64, 0x79, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x6f, 0x64, 0x6f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_todo_v1_event_proto_rawDescOnce sync.Once
	file_todo_v1_event_proto_rawDescData = file_todo_v1_event_proto_rawDesc
)

func file_todo_v1_event_proto_rawDescGZIP() []byte {
	file_todo_v1_event_proto_rawDescOnce.Do(func() {
		file_todo_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_todo_v1_event_proto_rawDescData)
	})
	return file_todo_v1_event_proto_rawDescData
}

var file_todo_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_todo_v1_event_proto_goTypes = []interface{}{
	(Event)(0), // 0: todo.v1.Event
}
var file_todo_v1_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_todo_v1_event_proto_init() }
func file_todo_v1_event_proto_init() {
	if File_todo_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todo_v1_event_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_todo_v1_event_proto_goTypes,
		DependencyIndexes: file_todo_v1_event_proto_depIdxs,
		EnumInfos:         file_todo_v1_event_proto_enumTypes,
	}.Build()
	File_todo_v1_event_proto = out.File
	file_todo_v1_event_proto_rawDesc = nil
	file_todo_v1_event_proto_goTypes = nil
	file_todo_v1_event_proto_depIdxs = nil
}
