name: build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.16.x, 1.17.x]
        node: [16, 14]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.1.0
      with:
        node-version: ${{ matrix.node }}
        cache: npm
    - run: npm install

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-${{ matrix.go }}

    - name: build
      run: |
        go run tools/mage.go build:front
        go run tools/mage.go build:backend
